#!/bin/bash

export CONTENT=$1
export FILE=$CONTENT\x0a\x0d
export SUM=($(echo -n $FILE | md5sum))

echo $FILE | curl --data-binary "@-" -X POST "http://192.168.1.15:8080/test/cmd/mcu?md5=${SUM[0]^^}"
